export const STATES = [
  { abbr: 'AL', id: '01', name: 'Alabama', color: '#4C5896' },
  { abbr: 'AK', id: '02', name: 'Alaska', color: '#0AE044' },
  { abbr: 'AZ', id: '04', name: 'Arizona', color: '#E4197D' },
  { abbr: 'AR', id: '05', name: 'Arkansas', color: '#86C5E9' },
  { abbr: 'CA', id: '06', name: 'California', color: '#CDF504' },
  { abbr: 'CO', id: '08', name: 'Colorado', color: '#231449' },
  { abbr: 'CT', id: '09', name: 'Connecticut', color: '#3CFFC8' },
  { abbr: 'DE', id: '10', name: 'Delaware', color: '#45455E' },
  { abbr: 'DC', id: '11', name: 'District of Columbia', color: '#341B83' },
  { abbr: 'FL', id: '12', name: 'Florida', color: '#69CE26' },
  { abbr: 'GA', id: '13', name: 'Georgia', color: '#0CCE8B' },
  { abbr: 'HI', id: '15', name: 'Hawaii', color: '#440800' },
  { abbr: 'ID', id: '16', name: 'Idaho', color: '#211B8F' },
  { abbr: 'IL', id: '17', name: 'Illinois', color: '#95CE32' },
  { abbr: 'IN', id: '18', name: 'Indiana', color: '#150C17' },
  { abbr: 'IA', id: '19', name: 'Iowa', color: '#B65D0A' },
  { abbr: 'KS', id: '20', name: 'Kansas', color: '#F5A00D' },
  { abbr: 'KY', id: '21', name: 'Kentucky', color: '#39AAFE' },
  { abbr: 'LA', id: '22', name: 'Louisiana', color: '#596625' },
  { abbr: 'ME', id: '23', name: 'Maine', color: '#A06CC0' },
  { abbr: 'MD', id: '24', name: 'Maryland', color: '#DC50C1' },
  { abbr: 'MA', id: '25', name: 'Massachusetts', color: '#4B1B06' },
  { abbr: 'MI', id: '26', name: 'Michigan', color: '#7DDC3E' },
  { abbr: 'MN', id: '27', name: 'Minnesota', color: '#7D2AE1' },
  { abbr: 'MS', id: '28', name: 'Mississippi', color: '#C815D2' },
  { abbr: 'MO', id: '29', name: 'Missouri', color: '#B36729' },
  { abbr: 'MT', id: '30', name: 'Montana', color: '#6906D3' },
  { abbr: 'NE', id: '31', name: 'Nebraska', color: '#4A05D4' },
  { abbr: 'NV', id: '32', name: 'Nevada', color: '#DFFF8A' },
  { abbr: 'NH', id: '33', name: 'New Hampshire', color: '#7B215A' },
  { abbr: 'NJ', id: '34', name: 'New Jersey', color: '#DF690A' },
  { abbr: 'NM', id: '35', name: 'New Mexico', color: '#F15008' },
  { abbr: 'NY', id: '36', name: 'New York', color: '#505F8F' },
  { abbr: 'NC', id: '37', name: 'North Carolina', color: '#40E9B9' },
  { abbr: 'ND', id: '38', name: 'North Dakota', color: '#1BA0CA' },
  { abbr: 'OH', id: '39', name: 'Ohio', color: '#759CE1' },
  { abbr: 'OK', id: '40', name: 'Oklahoma', color: '#2D4DA1' },
  { abbr: 'OR', id: '41', name: 'Oregon', color: '#4C645C' },
  { abbr: 'PA', id: '42', name: 'Pennsylvania', color: '#2BCA3B' },
  { abbr: 'RI', id: '44', name: 'Rhode Island', color: '#7CA252' },
  { abbr: 'SC', id: '45', name: 'South Carolina', color: '#9EDB04' },
  { abbr: 'SD', id: '46', name: 'South Dakota', color: '#E2DF4B' },
  { abbr: 'TN', id: '47', name: 'Tennessee', color: '#14FEDB' },
  { abbr: 'TX', id: '48', name: 'Texas', color: '#D0DB0E' },
  { abbr: 'UT', id: '49', name: 'Utah', color: '#B6840C' },
  { abbr: 'VT', id: '50', name: 'Vermont', color: '#591DE9' },
  { abbr: 'VA', id: '51', name: 'Virginia', color: '#C7284C' },
  { abbr: 'WA', id: '53', name: 'Washington', color: '#1E753C' },
  { abbr: 'WI', id: '55', name: 'West Virginia', color: '#450B40' },
  { abbr: 'WV', id: '54', name: 'Wisconsin', color: '#143B80' },
  { abbr: 'WY', id: '56', name: 'Wyoming', color: '#9C0E98' },
]

export const STATE_ABBREVS = STATES.map(state => state.abbr)
